
  services:
    postgres:
      image: postgres:latest
      container_name: postgres-db
      environment:
        POSTGRES_USER: jira
        POSTGRES_PASSWORD: JiraRush
        POSTGRES_DB: jira
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U jira -d jira"]
        interval: 10s
        timeout: 5s
        retries: 5

    jira-app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: jira-app
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/jira
        SPRING_DATASOURCE_USERNAME: jira
        SPRING_DATASOURCE_PASSWORD: JiraRush
        APP_HOST_URL: http://localhost
      ports:
        - "8080:8080"
      depends_on:
        postgres:
          condition: service_healthy
      restart: unless-stopped

    nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./resources:/opt/jirarush/resources
        - ./attachments:/opt/jirarush/attachments
      ports:
        - "80:80"
      depends_on:
        - jira-app
      restart: unless-stopped


